
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSleftASTERLETTER PLUS LPAREN RPAREN ASTER NONEexpression : termterm : factorfactor : LETTERfactor : NONEexpression : expression PLUS termterm : term factorfactor : LPAREN expression RPARENfactor : factor ASTER'
    
_lr_action_items = {'LETTER':([0,2,3,4,5,6,7,8,9,11,12,],[4,4,-2,-3,-4,4,4,-6,-8,4,-7,]),'NONE':([0,2,3,4,5,6,7,8,9,11,12,],[5,5,-2,-3,-4,5,5,-6,-8,5,-7,]),'LPAREN':([0,2,3,4,5,6,7,8,9,11,12,],[6,6,-2,-3,-4,6,6,-6,-8,6,-7,]),'$end':([1,2,3,4,5,8,9,11,12,],[0,-1,-2,-3,-4,-6,-8,-5,-7,]),'PLUS':([1,2,3,4,5,8,9,10,11,12,],[7,-1,-2,-3,-4,-6,-8,7,-5,-7,]),'RPAREN':([2,3,4,5,8,9,10,11,12,],[-1,-2,-3,-4,-6,-8,12,-5,-7,]),'ASTER':([3,4,5,8,9,12,],[9,-3,-4,9,-8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,],[1,10,]),'term':([0,6,7,],[2,2,11,]),'factor':([0,2,6,7,11,],[3,8,3,3,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term','expression',1,'p_expression','py.py',48),
  ('term -> factor','term',1,'p_term','py.py',52),
  ('factor -> LETTER','factor',1,'p_factor','py.py',56),
  ('factor -> NONE','factor',1,'p_none','py.py',60),
  ('expression -> expression PLUS term','expression',3,'p_plus','py.py',64),
  ('term -> term factor','term',2,'p_series','py.py',68),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_parens','py.py',72),
  ('factor -> factor ASTER','factor',2,'p_asterisk','py.py',76),
]
